name: Scholarship Bot Scheduler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# 깃허브 내부 서버 경고창(Node.js) 안 뜨게 숨기는 마법의 주문
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 내 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설치하기
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 필요한 파이썬 부품 설치
        run: pip install requests beautifulsoup4

      - name: 봇 실행하기!
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: 봇이 확인한 새 글 번호 메모장에 저장하고 덮어쓰기
        continue-on-error: true # ✨ 꿀팁: 덮어쓸 내용이 없어서 에러가 나더라도 무시하고 성공으로 넘어가!
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add last_post_id.txt
          git commit -m "봇 기억 업데이트"
          git push
